### ISSUE TITLE
How to cast AirStep

### ISSUE THREAD

**Issue by Summeryyy03** [snackerpirater/aero-additions#1]
I'm trying to cast the AirStep spell, but I'm not getting it right. Every time I try it just says "AirStep cannot be cast from a spells"

How can i cast?

**Comment by snackerpirater** [comment]
I assume you're trying to cast Airstep from a scroll. Since Airstep is a multi-cast (multiple use) spell, it can't be cast from a scroll; you have to put the scroll into a spellbook.
